CREATE TABLE [quality] (
[id] INTEGER  PRIMARY KEY NOT NULL,
[name] VARCHAR(50)  NOT NULL,
[bitrate] INTEGER DEFAULT 0 NOT NULL,
[width] INTEGER DEFAULT 0 NOT NULL,
[height] INTEGER DEFAULT 0 NOT NULL,
[admin_only] BOOLEAN DEFAULT 1 NOT NULL
);

CREATE TABLE [user] (
[id] INTEGER DEFAULT 0 NOT NULL PRIMARY KEY,
[admin] BOOLEAN DEFAULT 0 NOT NULL,
[username] VARCHAR(255)  UNIQUE NOT NULL,
[password] VARCHAR(255)  NOT NULL,
[email] VARCHAR(255) DEFAULT NULL NULL,
[watched_status] BOOLEAN DEFAULT 0 NOT NULL,
[max_quality_id] INTEGER DEFAULT 0 NOT NULL,
[default_quality_id] INTEGER DEFAULT 0 NOT NULL,
[max_mobile_quality] INTEGER DEFAULT 0 NOT NULL,
[default_mobile_quality] INTEGER DEFAULT 0 NOT NULL
);
